// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Generated by stoke create — replace every TODO before running.

import {StokeOperation, OperationRunner, Context, JsonSource, Logger, Config, LoggerLib} from "stoke/Stoke.sol";
import {IERC20} from "forge-std/interfaces/IERC20.sol";
import {ISeaportMinimal} from "./interfaces/ISeaportMinimal.sol";
import {BuildOrderLib} from "./BuildOrderLib.sol";

library BuildOrderLib {
    using Config for JsonSource;

    bytes32 internal constant NO_CONDUIT = bytes32(0);

    struct TokenAndAmount {
        IERC20 token;
        uint256 amount;
    }

    struct Order {
        TokenAndAmount[] offers;
        TokenAndAmount[] asks;
        address askRecipient;
        uint256 startTimestamp;
        uint256 endTimestamp;
        bytes salt;
    }

    function minimalOrderParams(Context memory ctx, address multisig) internal view returns (Order memory) {
        TokenAndAmount[] memory offers = new TokenAndAmount[](1);
        offers[0] = TokenAndAmount({
            token: IERC20(ctx.config.externalAddresses.requiredAddress(".lido.stETH")),
            amount: ctx.config.settings.requiredAmount(".rageQuit.stETH-offer-amount")
        });
        TokenAndAmount[] memory asks = new TokenAndAmount[](2);
        asks[0] = TokenAndAmount({
            token: IERC20(ctx.config.deployed.requiredAddress(".STRAT")),
            amount: ctx.config.settings.requiredAmount(".rageQuit.STRAT-ask-amount")
        });
        asks[1] = TokenAndAmount({
            token: IERC20(ctx.config.externalAddresses.requiredAddress(".sky-money.USDS")),
            amount: ctx.config.settings.requiredAmount(".rageQuit.USDS-ask-amount")
        });
        return Order({
            offers: offers,
            asks: asks,
            askRecipient: multisig,
            startTimestamp: ctx.config.settings.requiredUint(".rageQuit.start-timestamp"),
            endTimestamp: ctx.config.settings.requiredUint(".rageQuit.end-timestamp"),
            salt: bytes(ctx.config.settings.requiredString(".rageQuit.salt"))
        });
    }

    function constructOrderParams(address multisig, Order memory order)
        internal
        pure
        returns (ISeaportMinimal.OrderParameters memory)
    {
        ISeaportMinimal.OfferItem[] memory offer = new ISeaportMinimal.OfferItem[](order.offers.length);
        for (uint256 i; i < order.offers.length; ++i) {
            offer[i] = ISeaportMinimal.OfferItem({
                itemType: ISeaportMinimal.ItemType.ERC20,
                token: address(order.offers[i].token),
                identifierOrCriteria: 0,
                startAmount: order.offers[i].amount,
                endAmount: order.offers[i].amount
            });
        }

        ISeaportMinimal.ConsiderationItem[] memory consideration =
            new ISeaportMinimal.ConsiderationItem[](order.asks.length);
        for (uint256 i; i < order.asks.length; ++i) {
            consideration[i] = ISeaportMinimal.ConsiderationItem({
                itemType: ISeaportMinimal.ItemType.ERC20,
                token: address(order.asks[i].token),
                identifierOrCriteria: 0,
                startAmount: order.asks[i].amount,
                endAmount: order.asks[i].amount,
                recipient: payable(order.askRecipient)
            });
        }

        return ISeaportMinimal.OrderParameters({
            offerer: multisig,
            zone: address(0),
            offer: offer,
            consideration: consideration,
            orderType: ISeaportMinimal.OrderType.PARTIAL_OPEN,
            startTime: order.startTimestamp,
            endTime: order.endTimestamp,
            zoneHash: bytes32(0),
            salt: uint256(keccak256(order.salt)),
            conduitKey: NO_CONDUIT,
            totalOriginalConsiderationItems: consideration.length
        });
    }
}
